server:
  port: 8080

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/m245_magento?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 10079894

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pactera.learn.spring.mapper